CI: Add curl actuator && health check

diff --git a/.github/workflows/ci-scrape-api.yml b/.github/workflows/ci-scrape-api.yml
--- a/.github/workflows/ci-scrape-api.yml
+++ b/.github/workflows/ci-scrape-api.yml
@@ -5,7 +5,7 @@ on:
   #  paths-ignore:
   #    - '**'
   schedule: # Ref https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
-    - cron: '*/45 * * * *' # Ref https://crontab.guru/examples.html
+    - cron: '*/15 * * * *' # Ref https://crontab.guru/examples.html
   
 env:
   BRANCH_NAME: 'main'
@@ -20,11 +20,24 @@ jobs:
       js: ${{ steps.changes.outputs.js }}
     
     steps: # Make sure we have some code to diff
+      - name: curl actuator
+        id: ping
+        run: |
+          echo "::set-output name=status::$(curl https://www.roi.ru/api/attributes/status.json)"
+      
+      - name: health check
+        run: |
+          if [[ ${{ steps.ping.outputs.status }} != *"UP"* ]]; then
+            echo "health check is failed"
+            exit 1
+          fi
+          echo "It's OK"
+      
       - name: Checkout repository
         uses: actions/checkout@main
         with:
           fetch-depth: 0
-
+      
       - name: Get changed files
         id: changes # Set outputs using the command.
         run: |
@@ -34,7 +47,7 @@ jobs:
   deploy_and_scrape:
     name: Scrape query
     permissions: # Ref https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
-      - contents: write
+      contents: write
     runs-on: ubuntu-latest
     needs: changed_files
     timeout-minutes: 5
