CI: Remove curl actuator && health check

diff --git a/.github/workflows/ci-scrape-api.yml b/.github/workflows/ci-scrape-api.yml
--- a/.github/workflows/ci-scrape-api.yml
+++ b/.github/workflows/ci-scrape-api.yml
@@ -5,7 +5,7 @@ on:
   #  paths-ignore:
   #    - '**'
   schedule: # Ref https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
-    - cron: '*/15 * * * *' # Ref https://crontab.guru/examples.html
+    - cron: '*/45 * * * *' # Ref https://crontab.guru/examples.html
   
 env:
   BRANCH_NAME: 'main'
@@ -15,23 +15,24 @@ jobs:
   changed_files:
     name: Check modified files
     runs-on: ubuntu-latest
+    timeout-minutes: 2
     outputs: # Map a step output to a job output
       all: ${{ steps.changes.outputs.all }}
       js: ${{ steps.changes.outputs.js }}
     
     steps: # Make sure we have some code to diff
-      - name: curl actuator
-        id: ping
-        run: |
-          echo "::set-output name=status::$(curl https://www.roi.ru/api/attributes/status.json)"
+    #  - name: curl actuator
+    #    id: ping
+    #    run: |
+    #      echo "::set-output name=status::$(curl https://www.roi.ru/api/attributes/status.json)"
       
-      - name: health check
-        run: |
-          if [[ ${{ steps.ping.outputs.status }} != *"UP"* ]]; then
-            echo "health check is failed"
-            exit 1
-          fi
-          echo "It's OK"
+    #  - name: health check
+    #    run: |
+    #      if [[ ${{ steps.ping.outputs.status }} != *"UP"* ]]; then
+    #        echo "health check is failed"
+    #        exit 1
+    #      fi
+    #      echo "It's OK"
       
       - name: Checkout repository
         uses: actions/checkout@main
@@ -39,7 +40,7 @@ jobs:
           fetch-depth: 0
       
       - name: Get changed files
-        id: changes # Set outputs using the command.
+        id: changes # Set outputs using the command
         run: |
           echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
           echo "::set-output name=js::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .json$ | xargs)"
@@ -50,7 +51,6 @@ jobs:
       contents: write
     runs-on: ubuntu-latest
     needs: changed_files
-    timeout-minutes: 5
     if: ${{ needs.changed_files.outputs.js }} && contains( github.ref, 'refs/heads/main' ) || contains( github.ref, 'refs/heads/master' )
 
     steps:
